name: grism_overlap
channels:
  - conda-forge
  - http://ssb.stsci.edu/astroconda
  - defaults
dependencies:
  - astropy=4.0
  - healpy=1.11.0
  - click=7.0
  - ipython=7.12.0
  - jupyter=1.0.0
  - numpy=1.18.1
  - pytest=5.4.3
  - python=3.6.8
  - scipy=1.2.1
  - pysiaf
  - matplotlib
  - tk
  - pip:
    - numpydoc==0.8.0
    - extension-helpers==1.0.0